server:
  port: 8001

spring:
  datasource:
    url: jdbc:shardingsphere:classpath:sharding-sphere-${database.env:dev}.yaml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 4747

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


  mvc:
    view:
      prefix: /templates/
      suffix: .html